---
- name: Restart Traefik container
  ansible.builtin.command:
    argv:
      - docker
      - restart
      - "{{ traefik_container_name }}"
  changed_when: true
- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    enabled: true
