# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Use custom format
format = """
[╭─](bold blue)$env_var$directory$git_branch$git_status\n[╰─](bold blue)$character"""

# Disable the package module, hiding it from the prompt
[package]
disabled = true

# Use custom prompt character
[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

# Directory format
[directory]
style = "bold cyan"
read_only = " "
truncation_length = 3
format = " ➜  [$path]($style)"

# Show the project name when provided in .env
[env_var.PROJECT_NAME]
format = " [$env_value]($style)"
style = "bold cyan"

[env_var.DEVCONTAINER_CONTEXT]
format = " ([$env_value]($style))"
style = "bold blue"

[line_break]
disabled = false

# Git branch format
[git_branch]
symbol = ""
style = "bold purple"
format = " ➜  branch: [$branch]($style)"

# Git status format
[git_status]
style = "bold red"
format = '[\[$all_status$ahead_behind\]]($style)'
disabled = false

# Node.js format
[nodejs]
symbol = " "
style = "bold green"
format = "[$symbol($version )]($style)"
disabled = true

# Python format
[python]
symbol = " "
style = "bold yellow"
format = "[$symbol($version )]($style)"
disabled = true

# Docker context format
[docker_context]
symbol = " "
style = "bold blue"
format = "[$symbol$context]($style) "
disabled = true 
