---
pihole_sync_required_env_vars:
  - PIHOLE_SYNC_ENABLED
  - PIHOLE_PRIMARY_URL
  - PIHOLE_PRIMARY_IP
  - PIHOLE_TRAEFIK_ENABLED
  - PIHOLE_SYNC_VERIFY_ENABLED

pihole_sync_enabled: "{{ lookup('env', 'PIHOLE_SYNC_ENABLED') }}"
pihole_primary_url: "{{ lookup('env', 'PIHOLE_PRIMARY_URL') }}"
pihole_primary_ip: "{{ lookup('env', 'PIHOLE_PRIMARY_IP') }}"
pihole_traefik_enabled: "{{ lookup('env', 'PIHOLE_TRAEFIK_ENABLED') }}"
pihole_sync_verify_enabled: "{{ lookup('env', 'PIHOLE_SYNC_VERIFY_ENABLED') }}"
pihole_sync_verify_password: "{{ lookup('env', 'PIHOLE_SYNC_VERIFY_PASSWORD') }}"
pihole_compose_dir: "/srv/apps/pihole"
pihole_compose_file: "/srv/apps/pihole/docker-compose.yml"
